### ISSUE TITLE
External DTD Validation not working

### ISSUE THREAD

**Issue by vaibhav-bansal** [eerohele/exalt#8] opened 2017-03-25 12:39 UTC
Exalt doesn't detect the external DTD file or maybe it detects but can't read the definitions in the file when I select <b>Validate Document</b>. It works perfectly with Internal DTD and XSD files.
And thank you for making this plugin. Really made my work easy.

<h3>1. Summary</h3>
Doesn't read the DTD definitions in the external DTD file.

<h3>2. Expected Behavior</h3>
Should notify "Valid markup".

<h3>3. Actual Behavior</h3>
Didn't read the definitions and notified "No declarations for element bookDB".

<h3>4. Code Used</h3>
<b>XML File- bookDB.xml</b>

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE bookDB SYSTEM "bookDB.dtd">

<bookDB>
	<book>
		<name>Five Point Someone</name>
		<author>Chetan Bhagat</author>
	</book>
	<book>
		<name>I Too Had A Love Story!</name>
		<author>Ravindra Singh</author>
	</book>
	<book>
		<name>Goosebumps - The Werewolf of Fever Swamp</name>
		<author>R. L. Stine</author>
	</book>
</bookDB>
```

<b>DTD File- bookDB.dtd</b>
```
<!ELEMENT bookDB (book+)>
<!ELEMENT book (name,author)>
<!ELEMENT name (CDATA)>
<!ELEMENT author (CDATA)>

```
<h3>5. Environment</h3>
<b>Operating System:</b>
Windows 8.1 x64 EN<br>
<b>Sublime Text:</b>
Build 3126<br><br>
Thanks.

**Comment by eerohele** [comment] 2017-03-27 08:56
Glad to hear you find it useful!

Yeah, Exalt [doesn't support SYSTEM identifiers](https://github.com/eerohele/exalt/blob/4c9c05c9950cdcdc582934bfa7f38de66130e6c6/impl/validator.py#L91) at the moment. I'll see what I can do about that.

**Comment by eerohele** [comment] 2017-03-30 07:09
@vaibhav-bansal: v0.3.2 should fix the issue. Can you try updating the plugin, restarting Sublime Text, and checking whether the issue is fixed for you?

**Comment by vaibhav-bansal** [comment] 2017-03-31 03:41
Thanks for the update. Yes it worked.
I checked it with the same code I posted above. Now, it's detecting the external DTD and validating it correctly.
But, there's an issue.
When I change the definitions in the DTD file, it is not able to validate it right away.
I have to restart Sublime to validate the changes.

**Comment by vaibhav-bansal** [comment] 2017-03-31 03:42
Thanks for the update and yes, it worked.
I checked it with the same code I posted above. Now, it's detecting the external DTD and validating it correctly.
But, there's an issue.
When I change the definitions in the DTD file, it is not able to validate it right away.
I have to restart Sublime to validate the changes.
Thanks :)

**Comment by vaibhav-bansal** [comment] 2017-03-31 03:42
Thanks for the update and yes, it worked.
I checked it with the same code I posted above. Now, it's detecting the external DTD and validating it correctly.
But, there's an issue.
When I change the definitions in the DTD file, it is not able to validate it right away.
I have to restart Sublime to validate the changes.
Thanks

**Comment by vaibhav-bansal** [comment] 2017-03-31 03:43
Thanks for the update and yes, it worked.
I checked it with the same code I posted above. Now, it's detecting the external DTD and validating it correctly.
But, there's an issue.
When I change the definitions in the DTD file, it is not able to validate it right away.
I have to restart Sublime to validate the changes.
Thanks.

**Comment by eerohele** [comment] 2017-03-31 07:11
By default, Exalt caches the schema for a document for performance reasons.

You should be able to run the "Exalt: Clear Parser Cache" command after updating the DTD instead of restarting Sublime Text. Please let me know if that doesn't work, though.

**Comment by vaibhav-bansal** [comment] 2017-03-31 14:39
Yipee! It works perfectly. Thank you so much Sir!!
😄 😆

**Comment by eerohele** [comment] 2017-04-02 05:09
Glad to hear it. I'll close this one, but feel free to comment if you discover any other aspects related to this issue.

**Closed as completed by eerohele** 2017-04-02 05:09 UTC
Labels: bug
