### ISSUE TITLE
Validation error disappears from screen

### ISSUE THREAD

**Issue by stodge** [eerohele/exalt#20] opened 2019-01-04 19:55 UTC
If I select a line in an XML file that failed to validate against the XSD file, the error appears in the status bar at the bottom of the application. However, it disappears after a few seconds so I can no longer read the error. Is this expected? Are the errors logged anywhere else? Thanks

**Comment by eerohele** [comment] 2019-01-07 06:36
Not expected. Are you able to attach samples of the XML and XSD files you're working with to this issue?

**Comment by eerohele** [comment] 2019-02-23 12:45
This should be fixed in v0.3.7.

It'll a take a while to land in Package Control, but if you have the time, could you give it a go and let me know whether it fixes the issue for you?

**Comment by stodge** [comment] 2019-02-23 23:40
Thanks, I'll try to install it soon.

**Comment by eerohele** [comment] 2019-03-28 10:13
I'll close this, but if the issue isn't fixed for you, please let me know and I'll take another look.

**Closed as completed by eerohele** 2019-03-28 10:13 UTC
Labels: bug
